### ISSUE TITLE
Using $templateCache with $http

### ISSUE THREAD

**Issue by guncha** [Pathgather/popeye#2]
Could be an issue with the somewhat outdated Angular we're using, but looks like $templateCache and the cache used by $http tend to store responses  in a different format. $templateCache contains strings while the $http cache contains a response object with statusCode, body, headers and statusResponse. Hence, using one with the other should be avoided.

https://github.com/Pathgather/popeye/blob/master/src/popeye.coffee#L107

P.S. Looks like the example on the Angular docs page for $http is wrong, too. Here's a slightly modified version that show the actual value stored in the $templateCache: http://plnkr.co/edit/bRvQPxiw4D5ZCjo5biFG?p=preview

**Comment by NevilleS** [comment]
Hmm, I did some googling today and found [Angular issue #10630](https://github.com/angular/angular.js/issues/10630) with some background on this. I believe that the official Angular response is "you're doing it wrong" if you're expecting `$templateCache.get()` to have a particular value. Actually, `$http` has code to manage cache values stored as array values (i.e. via `$http` caching) or a string (i.e. you placed it there manually): https://github.com/angular/angular.js/blob/35aec525ef8ac6eb1e274e89627c5c04fbbaa3df/src/ng/http.js#L1046-L1050.

From Popeye's perspective, I should probably be using the `$templateRequest` service instead of `$http`, though, which (as of 1.4 when some changes were reverted) will actually populate `$templateCache` with strings instead of array details...

**Comment by NevilleS** [comment]
Also some interesting comments in the [closed PR here](https://github.com/angular/angular.js/pull/10646): "...For the record, the $templateCache is not designed to be accessed directly. You should always go through the $templateRequest..." :smile:

**Comment by guncha** [comment]
Well, I guess it's one of those "now I know" things.
