### ISSUE TITLE
More options

### ISSUE THREAD

**Issue by henev** [Pathgather/popeye#3]
Please provide options for click outside to close, escape to close, parent element, controller as, and bind to controller so that locals can be bind to the scope of the controller (no need of injecting them).

Thank you :)

**Comment by NevilleS** [comment]
Some of these are definitely supported, and if you don't mind clarifying the others I'm happy to make a few adjustments :smile:

Disable "click outside to close": the returned modal object has a `container` property that you can call `off("click")` on, but it'd be easy to make this an option too

Disable "escape the close": actually there's already an option for this, pass `keyboard: false` (I missed this in the documentation)

Change parent element: you mean other that `body`? It wouldn't be hard to support an option here either, but what would you set it to, and what's the benefit over just appending the the body?

Controller as: I'm just using `$controller`, so this is already supposed, just pass a string to the `controller` option like `controller: "myModalCtrl as ctrl"` and use `ctrl` in your template

Bind to controller: not sure what this would be used for, assuming you are referring to the `bindToController` option on a directive? If you just want to pass in some locals to be bound to the modal controller, you can use the `locals` options for that (e.g. `locals: { user_id: "NevilleS", repo: "Popeye" }`)

**Comment by henev** [comment]
Thank you for your response.

Changing the parent element will be nice if like in my case I have a sidebar that is fixed and I want to show the dialog and the overlay only in the main content area and to be still able to use the sidebar.

Controller as will be very useful if I have a lot of dialogs and I am using a service to dynamically load them. If I use controller as a string that means I should definitely register the controller in my module and won't be able to use controllers as functions. Not that it is a big deal but it'll be less work for the developer.

If I use `locals` I can't get the values from my controller's scope directly. I need to inject for example `repo` in the controller to get access to `"Popeye"`.

I was using Angular Material's dialogs before that but I am very unsatisfied with angular material and especially with the dialogs they provide. You can check the options there.

Anyway great work here. I really like your project and it fits very nice in my project. The resolve option is great :P

Keep up the good work,
Chris

**Comment by NevilleS** [comment]
I added the `click` and `keyboard` options just now to v1.0.5. I don't think I'm going to add the bind to controller syntax here since it's a bit messy - I'd want it to behave the same was as `$compile` does for directives, and I don't particularly even like how it works for directives! Remember, it doesn't actually remove the need for a `$scope`, it just places the scope bindings on the controller instead.

If you want the ability to directly bind variables to the controller scope, that's definitely possible using the `scope` and `controller` variables that the `PopeyeModal` instance exposes. You can bind whatever you want there :+1: 

For example:

``` javascript
var modal = Popeye.openModal(opts);
modal.controller.someString = "this string is on the modal controller instance";
modal.scope.someOtherString = "this string is on the modal scope";
```

I could certainly be talked into allowing anonymous functions for controllers too, but I don't necessarily thinks it's a great pattern, so I'll sit on that one for now! Happy to take a PR if you're passionate about it though :stuck_out_tongue:

**Comment by 0xmtn** [comment]
Hi @NevilleS,

When I try to use `modal.scope.someVar` it gives me "Cannot set property 'someVar' of undefined". I checked and it seems like modal has a property "scope", but when I try to access it, it becomes undefined.

How can I solve this?
